// Agency Bridge - Auto-generated by `agency openclaw install`
// Provides API communication with Agency's observability server

export const AGENCY_API_URL = "https://srv1318413.tailba1595.ts.net:8765";

export type AgencySwarmHierarchy = {
  root: AgencySwarmNode;
  fetchedAt: number;
};

export type AgencySwarmNode = {
  id: string;
  name: string;
  role: string;
  level: string;
  status: string;
  trustScore: number;
  currentTask?: string | null;
  children: AgencySwarmNode[];
  specialty?: string | null;
  emoji?: string | null;
  recentTasks?: Array<{ task: string; status: string; completedAt?: string }>;
  activeCount?: number;
};

export type AgencySwarmSnapshot = {
  swarms: AgencySwarmGroup[];
  fetchedAt: number;
  hasActiveSwarm: boolean;
  totalWorkers: number;
  activeWorkers: number;
};

export type AgencySwarmGroup = {
  id: string;
  repo: string;
  baseBranch: string;
  createdAt: string;
  status: string;
  workers: AgencySwarmWorker[];
};

export type AgencySwarmWorker = {
  id: string;
  name: string;
  status: string;
  startedAt?: string;
  completedAt?: string;
  taskSpec?: string;
  swarmId: string;
};

export type AgencyAgentDetail = {
  id: string;
  name: string;
  role: string;
  level: string;
  trustScore: number;
  status: string;
  currentTask?: string | null;
  specialty?: string | null;
  recentHistory: Array<{ task: string; status: string; cost?: number; completedAt?: string }>;
  assignedCards: Array<{ name: string; progress: number; list: string }>;
  totalCost: number;
  tasksCompleted: number;
  tasksFailed: number;
};

/**
 * Fetch swarm hierarchy from Agency API.
 * Returns null if Agency API is unavailable.
 */
export async function fetchAgencyHierarchy(): Promise<AgencySwarmHierarchy | null> {
  try {
    const res = await fetch(`${AGENCY_API_URL}/api/swarm/hierarchy`);
    if (res.ok) return await res.json();
  } catch (e) {
    console.debug("[Agency] Hierarchy fetch failed:", e);
  }
  return null;
}

/**
 * Fetch swarm snapshot from Agency API.
 */
export async function fetchAgencySnapshot(): Promise<AgencySwarmSnapshot | null> {
  try {
    const res = await fetch(`${AGENCY_API_URL}/api/swarm/snapshot`);
    if (res.ok) return await res.json();
  } catch (e) {
    console.debug("[Agency] Snapshot fetch failed:", e);
  }
  return null;
}

/**
 * Fetch agent detail from Agency API.
 */
export async function fetchAgencyAgentDetail(agentId: string): Promise<AgencyAgentDetail | null> {
  try {
    const res = await fetch(`${AGENCY_API_URL}/api/swarm/agent/${encodeURIComponent(agentId)}`);
    if (res.ok) return await res.json();
  } catch (e) {
    console.debug("[Agency] Agent detail fetch failed:", e);
  }
  return null;
}

/**
 * Check if Agency API is available.
 */
export async function isAgencyAvailable(): Promise<boolean> {
  try {
    const res = await fetch(`${AGENCY_API_URL}/api/health`);
    return res.ok;
  } catch {
    return false;
  }
}
